name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the version as needed

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Adjust if you're using a different build command

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP <<EOF
          cd /path/to/your/project
          git pull origin main  # Pull latest code from GitHub
          npm install  # Install dependencies
          npm run build  # Build the project
          pm2 restart your-app-name  # Restart app if using pm2, or any other deployment steps you need
        EOF

    - name: restart pm2
      run : pm2 restart server
